### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by markspivey** [gbrodman/order-tracking#190]
@gbrodman I'm trying to invoke Firefox as I seem to be having cache issues with using Chrome, but I am running into the following issue:

python get_tracking_numbers.py --firefox
Retrieving Amazon tracking numbers from email ...
Searching for emails since 29-Mar-2021
Found 1 unread Amazon shipping emails in the dates we searched.
Traceback (most recent call last):
  File "get_tracking_numbers.py", line 126, in <module>
    main()
  File "get_tracking_numbers.py", line 43, in main
    trackings = amazon_tracking_retriever.get_trackings()
  File "Documents\GitHub\order-tracking\lib\email_tracking_retriever.py", line 70, in get_trackings
    self.driver = self.log_in_if_necessary()
  File "Documents\GitHub\order-tracking\lib\amazon_tracking_retriever.py", line 194, in log_in_if_necessary
    driver = self.driver_creator.new()
  File "Documents\GitHub\order-tracking\lib\driver_creator.py", line 25, in new
    return self._new_firefox_driver(wait, page_load)
  File "Documents\GitHub\order-tracking\lib\driver_creator.py", line 120, in _new_firefox_driver
    options.headless = self.headless
AttributeError: 'DriverCreator' object has no attribute 'headless'

**Comment by markspivey** [comment]
Fixed by setting

`    options.headless = False`

in Row 120 of driver_creator.py.
