### ISSUE TITLE
Error thrown when attempting to write to blank Google Sheet

### ISSUE THREAD

**Issue by CydeWeys** [gbrodman/order-tracking#39]
The following error is thrown when attempting to write order information to a blank sheet for the first time.  It can be fixed by adding in a header row, but it should probably just work even when a header row hasn't yet been specified.

```
$ python3 get_tracking_numbers.py
Retrieving tracking numbers from email...
Searching for emails since 14-Jul-2019
Found 3 unread Amazon shipping emails in the dates we searched
Found 3 total tracking numbers
Uploading tracking numbers...
Adding results to Google Sheets
Exception thrown after looking at the emails. Marking all relevant emails as unread to reset.
Marked all as unread
Traceback (most recent call last):
  File "get_tracking_numbers.py", line 62, in <module>
    sheets_uploader.upload(groups_dict)
  File "/usr/local/google/home/mcilwain/Code/order-tracking/sheets_uploader.py", line 27, in upload
    self.upload_trackings(group_sheet_id, trackings)
  File "/usr/local/google/home/mcilwain/Code/order-tracking/sheets_uploader.py", line 46, in upload_trackings
    trackings = self._find_new_trackings(group_sheet_id, trackings)
  File "/usr/local/google/home/mcilwain/Code/order-tracking/sheets_uploader.py", line 63, in _find_new_trackings
    [value[0] for value in existing_values_result['values']])
KeyError: 'values'
```

**Comment by gbrodman** [comment]
Whoops, fixed.
