### ISSUE TITLE
Handle empty Amounts column

### ISSUE THREAD

**Issue by nunyabiz1982** [gbrodman/order-tracking#77]
I am using "Accounting" format but the cell is empty:

DevTools listening on ws://127.0.0.1:51392/devtools/browser/1c58b52a-2e91-4d8b-8163-3f2efc942246
[4992:9560:0918/124042.775:ERROR:ssl_client_socket_impl.cc(943)] handshake failed; returned -1, SSL error code 1, net_error -100
[4992:9560:0918/124052.772:ERROR:ssl_client_socket_impl.cc(943)] handshake failed; returned -1, SSL error code 1, net_error -100
Filling in cost adjustments if applicable
Traceback (most recent call last):
  File "reconcile.py", line 86, in <module>
    reconciliation_uploader.download_upload_clusters(all_clusters)
  File "c:\Users\sandod\Desktop\order-tracking-master\order-tracking-master\reconciliation_uploader.py", line 46, in download_upload_clusters
    self.fill_adjustments(all_clusters, base_sheet_id)
  File "c:\Users\sandod\Desktop\order-tracking-master\order-tracking-master\reconciliation_uploader.py", line 55, in fill_adjustments
    clusters.from_row, base_sheet_id, "Reconciliation")
  File "c:\Users\sandod\Desktop\order-tracking-master\order-tracking-master\objects_to_sheet.py", line 23, in download_from_sheet
    return [from_row_fn(header, value) for value in values]
  File "c:\Users\sandod\Desktop\order-tracking-master\order-tracking-master\objects_to_sheet.py", line 23, in <listcomp>
    return [from_row_fn(header, value) for value in values]
  File "c:\Users\sandod\Desktop\order-tracking-master\order-tracking-master\clusters.py", line 187, in from_row
    'Manual Cost Adjustment')]) if 'Manual Cost Adjustment' in header else 0.0
ValueError: could not convert string to float:

**Comment by gbrodman** [comment]
ok we should be more resilient when dealing with empty entries (for floats, we'll make them 0.0)
